#!/bin/bash

# Предварительно настраиваем Debconf на автоматический ответ "да" для всех запросов
export DEBIAN_FRONTEND=noninteractive

# Обновление системы и установка необходимых пакетов без запросов
apt-get update && apt-get -y upgrade
apt-get install -y zip nano openssl wget needrestart curl

# Скачивание и распаковка Xray
wget https://github.com/XTLS/Xray-core/releases/download/v1.8.1/Xray-linux-64.zip -O /tmp/Xray-linux-64.zip
mkdir -p /opt/xray
unzip /tmp/Xray-linux-64.zip -d /opt/xray
chmod +x /opt/xray/xray

# Создание и настройка сервиса systemd для Xray
cat <<EOF >/usr/lib/systemd/system/xray.service
[Unit]
Description=Xray Service
Documentation=https://github.com/xtls
After=network.target nss-lookup.target

[Service]
User=nobody
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
NoNewPrivileges=true
ExecStart=/opt/xray/xray run -config /opt/xray/config.json
Restart=on-failure
RestartPreventExitStatus=23
LimitNPROC=10000
LimitNOFILE=1000000

[Install]
WantedBy=multi-user.target
EOF

# Включение автозапуска Xray
systemctl enable xray

# Генерация параметров
UUID=$(/opt/xray/xray uuid)
X25519_KEYS=$(/opt/xray/xray x25519)
SHORT_ID=$(openssl rand -hex 8)

# Разбор сгенерированных ключей x25519
PRIVATE_KEY=$(echo "$X25519_KEYS" | grep 'Private key' | awk '{print $3}')
PUBLIC_KEY=$(echo "$X25519_KEYS" | grep 'Public key' | awk '{print $3}')

# Настройка конфигурационного файла Xray
cat <<EOF >/opt/xray/config.json
{
  "log": {
    "loglevel": "info"
  },
  "routing": {
    "rules": [],
    "domainStrategy": "AsIs"
  },
  "inbounds": [
    {
      "port": 443,
      "protocol": "vless",
      "tag": "vless_tls",
      "settings": {
        "clients": [
          {
            "id": "$UUID",
            "email": "user1@myserver",
            "flow": "xtls-rprx-vision"
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "tcp",
        "security": "none",
        "tlsSettings": {
          "alpn": [
            "http/1.1"
          ],
          "certificates": [
            {
              "certificateFile": "/path/to/fullchain.pem",
              "keyFile": "/path/to/privkey.pem"
            }
          ]
        }
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}
EOF

# Перезапуск Xray
systemctl restart xray

# Вывод сгенерированных параметров
echo "UUID: $UUID"
echo "Private key: $PRIVATE_KEY"
echo "Public key: $PUBLIC_KEY"
echo "Short ID: $SHORT_ID"

# Вывод внешнего IP-адреса сервера
SERVER_IP=$(curl -s ifconfig.me)
echo "Server IP: $SERVER_IP"
